#!/usr/bin/env python3
"""Generate the workout's audio cues.

The Figma file specifies no sound, only that the final three seconds of a
phase beep (annotation on nodes 0:4 and 0:195). These are synthesised tones
rather than recordings, so they stay tiny, need no licensing, and can be
regenerated by running this script:

    python3 tools/generate-cues.py

Each transition gets a distinct shape so they are told apart by ear: work
starts on a rising pair, rest falls to a single low tone, cooldown descends,
and completion is a rising arpeggio.
"""

import math
import struct
import wave
from pathlib import Path

SAMPLE_RATE = 44_100
AMPLITUDE = 0.35
FADE_SECONDS = 0.008  # Short attack/release, so tones do not click.

OUT_DIR = Path(__file__).resolve().parent.parent / "assets" / "audio"

# name -> sequence of (frequency Hz, duration seconds, gap-after seconds)
CUES: dict[str, list[tuple[float, float, float]]] = {
    # Final-three-seconds tick: brief and unobtrusive.
    "tick": [(880.0, 0.07, 0.0)],
    # Get ready: a single mid tone announcing the workout.
    "get-ready": [(784.0, 0.14, 0.0)],
    # Work starts: a rising pair, the most urgent cue.
    "exercise": [(988.0, 0.09, 0.04), (1318.5, 0.13, 0.0)],
    # Rest: one low, settled tone.
    "rest": [(587.3, 0.20, 0.0)],
    # Cooldown: descending, signalling the wind-down.
    "cooldown": [(440.0, 0.15, 0.02), (329.6, 0.22, 0.0)],
    # Complete: a rising major arpeggio.
    "complete": [
        (523.3, 0.12, 0.01),
        (659.3, 0.12, 0.01),
        (784.0, 0.12, 0.01),
        (1046.5, 0.26, 0.0),
    ],
}


def envelope(index: int, total: int) -> float:
    """Linear fade in and out, to keep the edges click-free."""
    fade = max(1, int(FADE_SECONDS * SAMPLE_RATE))
    if index < fade:
        return index / fade
    if index > total - fade:
        return max(0.0, (total - index) / fade)
    return 1.0


def render(segments: list[tuple[float, float, float]]) -> bytes:
    frames = bytearray()
    for frequency, duration, gap in segments:
        total = int(duration * SAMPLE_RATE)
        for index in range(total):
            value = math.sin(2 * math.pi * frequency * index / SAMPLE_RATE)
            sample = int(value * envelope(index, total) * AMPLITUDE * 32767)
            frames += struct.pack("<h", sample)
        frames += struct.pack("<h", 0) * int(gap * SAMPLE_RATE)
    return bytes(frames)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, segments in CUES.items():
        path = OUT_DIR / f"{name}.wav"
        with wave.open(str(path), "wb") as handle:
            handle.setnchannels(1)
            handle.setsampwidth(2)
            handle.setframerate(SAMPLE_RATE)
            handle.writeframes(render(segments))
        print(f"wrote {path.relative_to(OUT_DIR.parent.parent)} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
